---
- name: Run the AWX installation playbook.
  command: "ansible-playbook -i inventory install.yml -e postgres_data_dir={{ postgres_data_dir }} -e host_port=8080"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: False
