---
dhis2_demo_to_war:
  'dev': 'master/dev/dhis2-dev-master.war'
  '2.34': '2.34/dhis2-stable-2.34.0-rc3.war'
  '2.33': '2.33/dev/dhis2-dev-2.33.war'
  '2.32': '2.32/dev/dhis2-dev-2.32.war'
  '2.31': '2.31/dev/dhis2-dev-2.31.war'
  '2.31/2.31.0': '2.31/dhis2-stable-2.31.war'
  '2.30': '2.30/dev/dhis2-dev-2.30.war'

dhis2_demo_map:
  # development
  'dev': 'https://databases.dhis2.org/sierra-leone/dev/dhis2-db-sierra-leone.sql.gz'
  # 2.34 development
  '2.34': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  # 2.34 patches
  '2.34/2.34.0-rc': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  '2.34/2.34.0': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  # 2.33 development
  '2.33': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  # 2.33 patches
  '2.33/2.33.3-rc': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/2.33.3': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/2.33.2-rc': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/2.33.2': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/2.33.1-HF1': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/2.33.1': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/2.33.0': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  # 2.32 development
  '2.32': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  # 2.32 patches
  '2.32/2.32.4-rc': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/2.32.4': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/2.32.3': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/2.32.2': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/2.32.1': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/2.32.0': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  # 2.31 development
  '2.31': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  # 2.31 patches
  '2.31/2.31.9-rc': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.9': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.8': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.7': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.6': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.5': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.4': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.3': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.2': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.1': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/2.31.0': 'https://databases.dhis2.org/sierra-leone/2.31/2.31.0/dhis2-db-sierra-leone.sql.gz'
  # 2.30 and earlier
  '2.30': 'https://databases.dhis2.org/sierra-leone/2.30/dhis2-db-sierra-leone.sql.gz'
  '2.29': 'https://databases.dhis2.org/sierra-leone/2.29/dhis2-db-sierra-leone.sql.gz'
  '2.28': 'https://databases.dhis2.org/sierra-leone/2.28/dhis2-db-sierra-leone.sql.gz'
  '2.27': 'https://databases.dhis2.org/sierra-leone/2.27/dhis2-db-sierra-leone.sql.gz'
  '2.26': 'https://databases.dhis2.org/sierra-leone/2.26/dhis2-db-sierra-leone.sql.gz'
  '2.25': 'https://databases.dhis2.org/sierra-leone/2.25/dhis2-db-sierra-leone.sql.gz'
  # New schema
  # =========================

  # development
  # 2.34 development
  '2.34/dev/dhis2-dev-2.34.war': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  # 2.34 canary
  '2.34/canary/dhis2-canary-2.34.war': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  # 2.34 patches
  '2.34/dhis2-stable-2.34.0-rc.war': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  '2.34/dhis2-stable-2.34.0.war': 'https://databases.dhis2.org/sierra-leone/2.34/dhis2-db-sierra-leone.sql.gz'
  # 2.33 development
  '2.33/dev/dhis2-dev-2.33.war': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  # 2.33 canary
  '2.33/canary/dhis2-canary-2.33.war': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  # 2.33 patches
  '2.33/dhis2-stable-2.33.3.war': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/dhis2-stable-2.33.2.war': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/dhis2-stable-2.33.1.war': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  '2.33/dhis2-stable-2.33.0.war': 'https://databases.dhis2.org/sierra-leone/2.33/dhis2-db-sierra-leone.sql.gz'
  # 2.32 development
  '2.32/dev/dhis2-dev-2.32.war': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  # 2.32 canary
  '2.32/canary/dhis2-canary-2.32.war': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  # 2.32 patches
  '2.32/dhis2-stable-2.32.5.war': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/dhis2-stable-2.32.4.war': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/dhis2-stable-2.32.3.war': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  '2.32/dhis2-stable-2.32.2.war': 'https://databases.dhis2.org/sierra-leone/2.32/dhis2-db-sierra-leone.sql.gz'
  # 2.31 development
  '2.31/dev/dhis2-dev-2.31.war': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  # 2.31 canary
  '2.31/canary/dhis2-canary-2.31.war': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  # 2.31 patches
  '2.31/dhis2-stable-2.31.9.war': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/dhis2-stable-2.31.8.war': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/dhis2-stable-2.31.7.war': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'
  '2.31/dhis2-stable-2.31.6.war': 'https://databases.dhis2.org/sierra-leone/2.31/dhis2-db-sierra-leone.sql.gz'

  'master/dev/dhis2-dev-master.war': 'https://databases.dhis2.org/sierra-leone/dev/dhis2-db-sierra-leone.sql.gz'
  'dev/dhis.war': 'https://databases.dhis2.org/sierra-leone/dev/dhis2-db-sierra-leone.sql.gz'
  '2.30/dhis.war': 'https://databases.dhis2.org/sierra-leone/2.30/dhis2-db-sierra-leone.sql.gz'
  '2.29/dhis.war': 'https://databases.dhis2.org/sierra-leone/2.29/dhis2-db-sierra-leone.sql.gz'
  '2.28/dhis.war': 'https://databases.dhis2.org/sierra-leone/2.28/dhis2-db-sierra-leone.sql.gz'
  '2.27/dhis.war': 'https://databases.dhis2.org/sierra-leone/2.27/dhis2-db-sierra-leone.sql.gz'
  '2.26/dhis.war': 'https://databases.dhis2.org/sierra-leone/2.26/dhis2-db-sierra-leone.sql.gz'
  '2.25/dhis.war': 'https://databases.dhis2.org/sierra-leone/2.25/dhis2-db-sierra-leone.sql.gz'
