---
# vars file for dhis2.dhis2
postgresql_version: "10"
# postgresql_packages:
#   - postgresql-client-common
#   - postgresql-{{ postgresql_version }}
#   - postgresql-contrib
#   - libpq-dev
#   - postgresql-10-postgis-2.4
#   - postgresql-{{ postgresql_version }}-postgis-3
postgresql_packages:
  - postgresql-{{ postgresql_version }}
  - postgresql-contrib
  - libpq-dev
  - postgis
  - postgresql-client-common

postgresql_user: postgres
postgresql_group: postgres
postgresql_daemon: "postgresql"
#postgresql_daemon: "postgresql@{{ postgresql_version }}-main"
postgresql_restarted_state: "restarted"

postgresql_unix_socket_directories:
  - '/var/run/postgresql'

postgresql_data_dir: "{{ storage_path }}/postgresql/{{ postgresql_version }}/main"
postgresql_port_map:
  '10': '5432'
  '11': '5433'
  '12': '5434'
  '13': '5435'
postgresql_port: "{{ postgresql_port_map[postgresql_version] }}"

postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"

# DHIS 2 global configuration options that will be set in postgresql.conf.
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: data_directory
    value: "{{ postgresql_data_dir }}"
  - option: port
    value: "{{ postgresql_port }}"
  - option: max_locks_per_transaction
    value: 200
  - option: max_connections
    value: 700
  - option: shared_buffers
    value: 1000MB
  - option: work_mem
    value: 12MB
  - option: maintenance_work_mem
    value: 256MB
  - option: effective_cache_size
    value: 5000MB
  - option: wal_buffers
    value: 14MB
  - option: synchronous_commit
    value: off
  - option: wal_writer_delay
    value: 10000ms
  - option: checkpoint_completion_target
    value: 0.8
  - option: logging_collector
    value: on
  - option: log_directory
    value: 'log'
  - option: log_filename
    value: 'postgresql.log'
  - option: log_truncate_on_rotation
    value: on



postgresql_version_config_options: []


postgresql_databases: []
postgresql_users: []
