---
# vars file for dhis2.deploy
postgresql_user: postgres
postgresql_group: postgres

postgresql_daemon: "postgresql"
postgresql_restarted_state: "restarted"

postgresql_unix_socket_directories:
  - '/var/run/postgresql'

postgresql_data_dir: "{{ storage_path }}/postgresql/{{ __postgresql_version }}/main"

# DHIS 2 global configuration options that will be set in postgresql.conf.
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: max_locks_per_transaction
    value: 200
  - option: max_connections
    value: 700
  - option: shared_buffers
    value: 2000MB
  - option: work_mem
    value: 12MB
  - option: maintenance_work_mem
    value: 256MB
  - option: effective_cache_size
    value: 5000MB
  - option: wal_buffers
    value: 14MB
  - option: synchronous_commit
    value: off
  - option: wal_writer_delay
    value: 10000ms
  - option: checkpoint_completion_target
    value: 0.8
  - option: data_directory
    value: "{{ postgresql_data_dir }}"

postgresql_databases: []
postgresql_users: []
