---
# === Stop instance ==========
# stop the instance if running
- name: stop the instance
  systemd:
    state: stopped
    name: dhis2-{{ instance.name }}
  ignore_errors: yes


# === get the storage location =========
- name: set the instance locations
  set_fact:
    storage: "{{ storage_path | default('/var/lib') }}"


# === update nginx =========
- include: nginx_config.yml

# === systemd tomcat services ======
- name: remove tomcat as a systemd service
  file:
    path: "/etc/systemd/system/dhis2-{{ instance.name }}.service"
    state: absent

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes

# === Remove DB ==============
- name: remove db {{ instance.name }}
  include_role:
    name: geerlingguy.postgresql
    tasks_from: databases.yml
  vars:
    postgresql_databases:
      - name: "{{ instance.db_name }}"
        owner: "{{ instance.db_owner | default('dhis') }}"
        state: absent
# =========================

# === finally, clean DHIS 2 home =========
- file:
    path: "{{ storage }}/instances/{{ instance.name }}"
    state: absent
