---
- name: "(Install: APT OSs) Set APT NGINX Signing Key URL"
  set_fact:
    keysite: "{{ nginx_signing_key | default('http://nginx.org/keys/nginx_signing.key') }}"

- name: "(Install: APT OSs) Add APT NGINX Signing Key"
  apt_key:
    url: "{{ keysite | default('https://nginx.org/keys/nginx_signing.key') }}"
