---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604
  - distro: debian9

  # Test without running the full playbook.
  - distro: centos7
    playbook: test-no-playbook.yml

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests (increasing the travis_wait timeout).
  - tests/custom_travis_wait.sh ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
