---
# === update users table ==============
- name: update users table in {{ instance.db_name }}
  postgresql_query:
    db: "{{ instance.db_name }}"
    query: UPDATE users SET passwordlastupdated = {{ pass_last_updated }} WHERE username like {{ dhis2_username }}
