---
# === update users table ==============
- name: try to update password expiry
- block:
  - name: update users table in {{ instance.db_name }}
    postgresql_query:
      db: "{{ instance.db_name }}"
      query: UPDATE users SET passwordlastupdated = '{{ pass_last_updated }}' WHERE username like '{{ dhis2_username }}'

- rescue:
  - name: update userinfo table in {{ instance.db_name }}
    postgresql_query:
      db: "{{ instance.db_name }}"
      query: UPDATE userinfo SET passwordlastupdated = '{{ pass_last_updated }}' WHERE username like '{{ dhis2_username }}'
