---

- name: add landing page
  template:
    src: "index{{ dhis2_lander }}.html.j2"
    dest: "/usr/share/nginx/html/index.html"
    mode: 0644
    force: yes

- name: add maintenance pages
  copy:
    src: resources
    dest: "/usr/share/nginx/html/"
    mode: 0644
    force: yes
