---
- name: Check current Tomcat version
  command: "{{ storage }}/instances/{{ instance.name }}/tomcat/bin/version.sh"
  register: tomcat_version
  changed_when: false
  become: true

- name: Set facts for Tomcat upgrade
  set_fact:
    tomcat_old_version: "10.0.27"
    tomcat_new_version: "{{ tomcat_10_version }}"
    tomcat_download_url: "https://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_10_version }}/bin/apache-tomcat-{{ tomcat_10_version }}.tar.gz"
    tomcat_download_path: "/tmp/apache-tomcat-{{ tomcat_10_version }}.tar.gz"
    tomcat_extract_path: "/tmp/apache-tomcat-{{ tomcat_10_version }}"

- block:
    - name: Download new Tomcat version
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_download_path }}"

    - name: Extract Tomcat archive
      unarchive:
        src: "{{ tomcat_download_path }}"
        dest: "/tmp"
        remote_src: yes

    - name: Set ownership of extracted Tomcat files
      file:
        path: "{{ tomcat_extract_path }}"
        owner: "{{ dhis2_user | default('dhis') }}"
        group: "{{ dhis2_user | default('dhis') }}"
        recurse: yes
      become_user: root

    - name: Sync new Tomcat files
      synchronize:
        src: "{{ tomcat_extract_path }}/"
        dest: "{{ storage }}/instances/{{ instance.name }}/tomcat/"
        rsync_opts:
          - "--exclude=webapps/"
          - "--exclude=conf/server.xml"
          - "--exclude=bin/setclasspath.sh"
          - "--exclude=bin/startup.sh"
      delegate_to: "{{ inventory_hostname }}"
      become_user: root

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tomcat_download_path }}"
        - "{{ tomcat_extract_path }}"
      become_user: root
  when: >
    tomcat_old_version in tomcat_version.stdout or
    (force_tomcat_10_upgrade | default('') == 'force')
