---
- name: make sure glowroot is configured for multiple agents
  lineinfile:
    path: "{{ storage }}/glowroot/glowroot.properties"
    line: multi.dir=true
    create: yes

- file:
    path: "{{ storage }}/glowroot/agent-{{ instance.name }}/{{ item }}"
    owner: "{{ dhis2_user }}"
    group: "{{ dhis2_user }}"
    recurse: yes
    state: "{{ 'directory' if instance.state == 'present' else 'absent'}}"
  with_items:
    - data
    - logs
    - tmp


- name: add glowroot conf
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ storage }}/glowroot/agent-{{ instance.name }}/{{ item }}.json"
    owner: "{{ dhis2_user }}"
    group: "{{ dhis2_user }}"
    mode: 0644
  with_items:
    - admin
    - config
  when: instance.state != 'absent'

- name: add glowroot to nginx
  blockinfile:
    path: "/etc/nginx/dhis2_instances"
    block: |
        location /{{ instance.name }}_glowroot {
            proxy_pass                http://127.0.0.1:{{ instance.glowroot_port  | default(4000)}}/{{ instance.name }}_glowroot;
        }
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ instance.name }}-glowroot"
    state: "{{ instance.state }}"
  notify: reload nginx

- name: reload nginx
  systemd:
    state: reloaded
    name: nginx
