---
- name: facts holder
  set_fact:
    instance_update: "{{ instance }}"

# === DHIS 2 home =========
- include: dhis2_home.yml
- include: nginx_config.yml

  # handler to restart tomcat?
# =========================

# === PostgreSQL ==========
- name: Ensure PostgreSQL users are present for {{ inventory_hostname }}/{{ instance.name }}
  postgresql_user:
    name: "{{ instance.db_owner | default(dhis2_db_owner_default) }}"
    password: "{{ instance.db_owner_password | default(dhis2_db_owner_password_default) }}"
    role_attr_flags: CREATEDB,SUPERUSER
    state: present
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true


# === Deploy WAR ==============
- include: deploy_war.yml

# === Restore DB ==============
- include: restore_database.yml
# =========================

# =========================
# start the instance (using the server scripts)
# - include: dhis2_services.yml op="start-instance"

- name: start the {{ inventory_hostname }}/{{ instance.name }} instance
  systemd:
    state: started
    name: dhis2-{{ instance.name }}


- name: remove redirect from nginx config
  blockinfile:
    path: "/etc/nginx/dhis2_instances"
    block: |
        location /{{ instance.name }} {
            proxy_pass                http://127.0.0.1:{{ instance.tomcat_port }}/{{ instance.name }};
            proxy_redirect            off;
            proxy_set_header          Host               $host;
            proxy_set_header          X-Real-IP          $remote_addr;
            proxy_set_header          X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header          X-Forwarded-Proto  https;
            #proxy_cache               dhis;
        }
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ instance.name }}"
    state: "{{ instance.state }}"
  notify: reload nginx

- name: reload nginx
  systemd:
    state: reloaded
    name: nginx

# add to prometheus scrape config if monitoring is on- name: remove redirect from nginx config
- set_fact:
    scraper_content: "{{ lookup('template', 'templates/prometheus_scrapers.j2') }}"

- blockinfile:
    dest: /etc/hosts
    content: '{{ scraper_content }}'
    state: present

- name: "make sure we have all the facts"
  setup: ~

- name: add scraper to prometheus
  blockinfile:
    path: "{{ prometheus_config_dir }}/prometheus.yml"
    content: '{{ scraper_content }}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - PROMETHEUS"
    insertbefore: EOF
  notify: reload prometheus
  when: inventory_hostname == "test.performance.dhis2.org" or
        inventory_hostname == "test.performance32.dhis2.org"
  ignore_errors: yes


- name: wait for instance {{ inventory_hostname }}/{{ instance.name }} to start in order to run analytics
  uri:
    url: https://{{ inventory_hostname }}/{{ instance.name }}/api/resourceTables/analytics
    method: POST
    user: "{{ dhis2_admin_user }}"
    password: "{{ dhis2_admin_user_password }}"
    force_basic_auth: yes
    status_code: 200
  register: result
  until: result.status in [200, 401]
  retries: 90
  delay: 10
  when: (project is not defined and instance.db_demo is defined and instance.db_demo|length != 0) or (project == "sierra-leone")
  ignore_errors: yes


# === Run API requests if defined ==============
- name: Run API requests
  include: api_prepare_calls.yml
  when: API_REQUESTS is defined and ( API_REQUESTS | length != 0) and
        dhis2_api_requests is defined and ( dhis2_api_requests | length != 0)
