---
- name: ensure that the ssl config is complete
  command: "openssl dhparam -out dhparam.pem 4096"
  args:
    chdir: "/etc/ssl/certs"
    creates: "/etc/ssl/certs/dhparam.pem"


# - name: Migrate nginx config
#   shell: sed -n '/BEGIN DHIS2-INSTANCES/,/END DHIS2-INSTANCES/p' /etc/nginx/conf.d/default.conf > /etc/nginx/dhis2_instances; sed -i '/# .*DHIS2-INSTANCES/d'  /etc/nginx/dhis2_instances
#   args:
#     creates: /etc/nginx/dhis2_instances

- name: Check if dhis2.conf exists in sites-enabled
  stat:
    path: /etc/nginx/sites-enabled/dhis2.conf
  register: dhis2_conf_in_sites_enabled

- name: Configure nginx as default if dhis2.conf does not exist in sites-enabled
  template:
    src: "nginx{{ dhis2_nginx }}.dhis.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: 0644
    force: yes
  notify: reload nginx
  when: dhis2_conf_in_sites_enabled.stat.exists == false

- name: Configure nginx if dhis2.conf exists in sites-enabled
  template:
    src: "nginx{{ dhis2_nginx }}.dhis.conf.j2"
    dest: "/etc/nginx/sites-available/dhis2.conf"
    mode: 0644
    force: yes
  notify: reload nginx
  when: dhis2_conf_in_sites_enabled.stat.exists



- name: add DHIS 2 instances to nginx config
  blockinfile:
    path: "/etc/nginx/dhis2_instances"
    block: |
        location /{{ instance.name }} {
            proxy_pass                http://127.0.0.1:{{ instance.tomcat_port }}/{{ instance.name }};
            proxy_redirect            off;
            proxy_set_header          Host               $host;
            proxy_set_header          X-Real-IP          $remote_addr;
            proxy_set_header          X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header          X-Forwarded-Proto  https;
            #proxy_cache               dhis;
        }
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ instance.name }}"
    insertbefore: "# END DHIS2-INSTANCES:"
    state: "{{ instance.state }}"
  notify: reload nginx

- name: add landing page
  template:
    src: "index{{ dhis2_lander }}.html.j2"
    dest: "/usr/share/nginx/html/index.html"
    mode: 0644
    force: yes

- name: create resources directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/share/nginx/html/resources/css
    - /usr/share/nginx/html/resources/images

- name: add favicon
  get_url:
    url: "https://github.com/dhis2/dhis2-identity/raw/master/web/favicon_package/favicon.ico"
    dest: "/usr/share/nginx/html/resources/favicon.ico"
    mode: 0644
  ignore_errors: yes

- name: get icon
  get_url:
    url: "https://github.com/dhis2/dhis2-identity/raw/master/web/Icon%20only/Default/dhis2-icon-rgb-positive.png"
    dest: "/usr/share/nginx/html/resources/dhis2-icon-rgb-positive.png"
    mode: 0644
  ignore_errors: yes

- name: get master logo
  get_url:
    url: "https://github.com/dhis2/dhis2-identity/raw/master/web/Logo/Default/dhis2-logo-rgb-positive.png"
    dest: "/usr/share/nginx/html/resources/dhis2-logo-rgb-positive.png"
    mode: 0644
  ignore_errors: yes

- name: add maintenance pages
  copy:
    src: "{{ item }}"
    dest: "/usr/share/nginx/html/"
    mode: 0644
  with_items:
    - restore_db.html
    - deploy_war.html
    - stopped.html
    - under_development.html
    - resources

- name: add error pages
  template:
    src: "{{ item }}.j2"
    dest: "/usr/share/nginx/html/{{ item }}"
    mode: 0644
  with_items:
    - 4xx.html
    - 400.html
    - 401.html
    - 403.html
    - 404.html
    - 5xx.html
    - 500.html
    - 502.html
