---
- name: ensure that the ssl config is complete
  command: "openssl dhparam -out dhparam.pem 4096"
  args:
    chdir: "/etc/ssl/certs"
    creates: "/etc/ssl/certs/dhparam.pem"


- name: Migrate nginx config
  shell: sed -n '/BEGIN DHIS2-INSTANCES/,/END DHIS2-INSTANCES/p' /etc/nginx/conf.d/default.conf > /etc/nginx/dhis2_instances; sed -i '/# .*DHIS2-INSTANCES/d'  /etc/nginx/dhis2_instances
  args:
    creates: /etc/nginx/dhis2_instances

- name: configure nginx
  template:
    src: "nginx{{ dhis2_nginx }}.dhis.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: 0644
    force: yes
  notify: reload nginx

- name: add DHIS 2 instances to nginx config
  blockinfile:
    path: "/etc/nginx/dhis2_instances"
    block: |
        location /{{ instance.name }} {
            proxy_pass                http://127.0.0.1:{{ instance.tomcat_port }}/{{ instance.name }};
            proxy_redirect            off;
            proxy_set_header          Host               $host;
            proxy_set_header          X-Real-IP          $remote_addr;
            proxy_set_header          X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header          X-Forwarded-Proto  https;
            #proxy_cache               dhis;
        }
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ instance.name }}"
    insertbefore: "# END DHIS2-INSTANCES:"
    state: "{{ instance.state }}"
  notify: reload nginx

- name: add landing page
  template:
    src: "index{{ dhis2_lander }}.html.j2"
    dest: "/usr/share/nginx/html/index.html"
    mode: 0644
    force: yes

- name: create resources directory
  file:
    path: /usr/share/nginx/html/resources/css
    state: directory

- name: add favicon
  get_url:
    url: "https://github.com/dhis2/dhis2-identity/raw/master/web/favicon_package/favicon.ico"
    dest: "/usr/share/nginx/html/resources/favicon.ico"
    mode: 0644

- name: get icon
  get_url:
    url: "https://github.com/dhis2/dhis2-identity/raw/master/web/Icon%20only/Default/dhis2-icon-rgb-positive.png"
    dest: "/usr/share/nginx/html/resources/dhis2-icon-rgb-positive.png"
    mode: 0644

- name: get master logo
  get_url:
    url: "https://github.com/dhis2/dhis2-identity/raw/master/web/Logo/Default/dhis2-logo-rgb-positive.png"
    dest: "/usr/share/nginx/html/resources/dhis2-logo-rgb-positive.png"
    mode: 0644

- name: add maintenance pages
  copy:
    src: "{{ item }}"
    dest: "/usr/share/nginx/html/{{ item }}"
    mode: 0644
  with_items:
    - restore_db.html
    - deploy_war.html
    - stopped.html
    - resources/css/landing.css
    - resources/css/landing_taller.css

- name: add error pages
  template:
    src: "{{ item }}.js"
    dest: "/usr/share/nginx/html/{{ item }}"
    mode: 0644
  with_items:
    - 404.html
    - 50x.html
