---
# tasks file for dhis2.dhis2



- name: Execute SQL - force admin password
  postgresql_query:
    db: "{{ instance.db_name }}"
    query: UPDATE users SET password = %s WHERE username = %s
    positional_args:
    - '{{ dhis2_admin_user_password_hash }}'
    - '{{ dhis2_admin_user }}'
  become: true
  become_user: "{{ postgresql_user }}"
