---
- name: facts holder
  set_fact:
    instance_update: "{{ instance }}"

# === Stop instance ==========
# stop the instance if running
- name: stop the instance
  systemd:
    state: stopped
    name: dhis2-{{ instance.name }}
  ignore_errors: yes


# === get the storage location =========
- name: set the instance locations
  set_fact:
    storage: "{{ storage_path | default('/var/lib') }}"

# ===  Save a DB snapshot to s3
- name: save a DB snapshot to s3
  include: save_snapshot.yml
  vars:
    db_save_suffix: "_REMOVED"
  when:
    - backup_on_removal is not defined or ((backup_on_removal | bool) == true)


# === update nginx =========
- include: nginx_config.yml

- include: factualise_instance.yml

# === systemd tomcat services ======
- name: remove tomcat as a systemd service
  file:
    path: "/etc/systemd/system/dhis2-{{ instance.name }}.service"
    state: absent

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes


# === Taks a snapshot of DB? ======


# === Remove DB ==============
- name: remove db {{ instance.name }}
  include: databases.yml
  vars:
    postgresql_databases:
      - name: "{{ instance.db_name }}"
        owner: "{{ instance.db_owner | default('dhis') }}"
        port: "{{ postgresql_port_map[instance.postgresql_version] | default(omit) }}"
        state: absent
# =========================

# === finally, clean DHIS 2 home =========
- file:
    path: "{{ storage }}/instances/{{ instance.name }}"
    state: absent
