---
# tasks file for dhis2.transifex
- name: Synchronise DHIS2 instance with transifex
  script: sync_transifex.py -u {{ t_user }} -p {{ t_pass }} -s {{ t_server }} -k {{ t_package }} -j {{ t_project }} -t {{ t_txkey }}
  args:
    executable: python3
    chdir: "/tmp"
