---
# tasks file for dhis2.transifex
- name: Synchronise DHIS2 instance with transifex (full DB)
  script: sync_transifex.py -u {{ t_user }} -p {{ t_pass }} -s {{ t_server }} -k {{ t_package }} -j {{ t_project }} -t {{ t_txkey }}
  args:
    executable: python3
    chdir: "/tmp"
  when: t_package is defined and t_package|length


- name: Synchronise DHIS2 instance with transifex for packages
  include: packages.yml
  loop: "{{ meta_packages }}"
  loop_control:
    loop_var: meta_package
