---
galaxy_info:
  author: Aliaksandr Kharkevich
  role_name: "elastic_metricbeat"
  description: >
    Deploy Metricbeat: Lightweight Shipper for Metrics

  issue_tracker_url: https://github.com/kharkevich/ansible-elastic-metricbeat/issues

  license: Apache

  min_ansible_version: 2.4

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  github_branch: master

  platforms:
    - name: Debian
      versions:
        - stretch
    - name: Ubuntu
      versions:
        - xenial
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - elastic
    - metricbeat
    - beat

dependencies: []
