---
 - hosts: instance_host
   become: yes

   tasks:

   - name: Add a new user named {{ user_name }}
     user:
          name={{ user_name }}

   - name: Add {{ user_name }} user to the sudoers
     copy:
          dest: "/etc/sudoers.d/{{ user_name }}"
          content: "{{ user_name }}  ALL=(ALL)  NOPASSWD: ALL"

   - name: Deploy SSH Key
     authorized_key: user={{ user_name }}
                     key="{{ user_public_key }}"
                     state=present

   - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
     notify:
       - restart ssh

   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify:
       - restart ssh

   handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted
