---
- hosts: "{{ instance_host }}"
  strategy: free
  become: yes

  pre_tasks:
    # create custom fact file if not existing
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
    - name: "Insert custom fact file"
      template:
        src: "files/dhis2public.fact.j2"
        dest: /etc/ansible/facts.d/dhis2public.fact
        mode: 0755
    - name: "Re-run setup to use custom facts"
      setup: ~
    - debug:
        msg: "{{ ansible_local.dhis2public.instances }}"


  tasks:
    # change password expiry
    - name: change password expiry for dhis2 instance
      include_role:
        name: dhis2.dhis2
        tasks_from: change_password_expiry.yml
      loop: "{{ ansible_local.dhis2public.instances|default([]) }}"
      loop_control:
        loop_var: single_instance
      vars:
        instance:
          name: "{{ single_instance.name }}"
          db_name: "{{ single_instance.db_name }}"
      when:
        - single_instance.name == instance_name
