---
- hosts: "{{ instance_host }}"
  strategy: free
  become: yes

  vars_files:
    # include the vars mapping dhis2 war to demo db version
    - vars/demomap.yml

  pre_tasks:
    # create custom fact file if not existing
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
    - name: "Insert custom fact file"
      template:
        src: "files/dhis2.fact.j2"
        dest: /etc/ansible/facts.d/dhis2.fact
        mode: 0755
    - name: "Re-run setup to use custom facts"
      setup: ~
    - debug:
        msg: "{{ ansible_local.dhis2 }}"

    # ensure we have the necessary version of postgres available
    - include_vars: vars/postgresql.yml
    - include: shared/postgresql_multi.yml

  vars:
    dhis2_instances:
      - name: "{{ instance_name }}"
        description: "{{ instance_description | default('Training instance',true) }}"
        state: 'present'
        war_file: 'https://releases.dhis2.org/{{ instance_war }}'
        db_name: "{{ instance_name | regex_replace('\\.', '-') }}"
        db_demo: "{{ project }}/{{ instance_demo }}"
        tomcat_port: "{{ ansible_local.dhis2.tomcat.next_port }}"
        activemq_port: "{{ ansible_local.dhis2.activemq.next_port }}"
        artemis_port: "{{ ansible_local.dhis2.artemis.next_port }}"
        postgresql_version: "{{ postgresql_version }}"
        # set monitoring to true to generate metrics for prometheus/grafana
        monitoring: "{{ monitoring | default('NO') }}"
        hibernate_monitoring: "{{ hibernate_monitoring | default('NO') }}"
        # choose whether to have master control of the database (permission to save over it)
        master_control: "{{ master_control | default('false') }}"

  tasks:
  - name: debug the dhis2_instances
    debug:
      msg: "{{ dhis2_instances }}"
  - name: dhis2 instances
    include_role:
      name: dhis2.dhis2
