---
- hosts: qateam
  strategy: free
  become: yes

  pre_tasks:
    # create custom fact file if not existing
    - name: "Create custom fact directory"
      file:
        path: "/etc/ansible/facts.d"
        state: "directory"
    - name: "Insert custom fact file"
      template:
        src: "files/dhis2.fact.j2"
        dest: /etc/ansible/facts.d/dhis2.fact
        mode: 0755

  tasks:
  - name: certbot
    include_role:
      name: geerlingguy.certbot
  - name: dhis2 instances
    include_role:
      name: dhis2.deploy
