---
- hosts: elk
  become: yes

#  vars_files:
#    - vars.yml


  # pre_tasks:
  #   - name: ensure webupd8team ppa is absent
  #     apt_repository:
  #       repo: 'ppa:webupd8team/java'
  #       state: absent


  roles:
    - geerlingguy.java
    - nginxinc.nginx
    - geerlingguy.certbot
    - geerlingguy.elasticsearch
    - geerlingguy.logstash
    - geerlingguy.kibana
