---
- hosts: elk
  become: yes

#  vars_files:
#    - vars.yml


  # pre_tasks:
  #   - name: ensure webupd8team ppa is absent
  #     apt_repository:
  #       repo: 'ppa:webupd8team/java'
  #       state: absent


  pre_tasks:
    # Create a new primary partition
    # - parted:
    #     device: "{{ storage_device }}"
    #     number: 1
    #     state: present
    #   when: storage_device is defined
    # Create a ext4 filesystem on storage device and check disk blocks.
    - filesystem:
        fstype: ext4
        dev: "{{ storage_device }}"
      when: storage_device is defined

    - name: add mount point if necessary
      mount:
        path: "{{ storage_path }}"
        src: "{{ storage_device }}"
        fstype: ext4
        opts: defaults
        state: mounted
      when: storage_device is defined


  tasks:
  # set up users and directories
  # add users
  - group:
      name: elasticsearch
      state: present
  - user:
      name: elasticsearch
      group: elasticsearch
  - name: java
    include_role:
      name: geerlingguy.java
  - name: nginx
    include_role:
      name: nginxinc.nginx
  - name: certbot
    include_role:
      name: geerlingguy.certbot
  - name: elasticsearch
    include_role:
      name: geerlingguy.elasticsearch
  - name: kibana
    include_role:
      name: geerlingguy.kibana
  - name: logstash
    include_role:
      name: geerlingguy.logstash
