---
- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    # include the vars for authentication when synchronising
    - vars/sync_translations.yml


  tasks:
  - name: synchronise
    include_role:
      name: dhis2.transifex
